import { Chain } from './template';

export const kusama: Chain = {
  name: 'kusama',
  nativeTokenUniqueId: 'KSM',
  label: 'Kusama',
  type: 'mainnet',
  theme: {
    colors: ['#000000', '#7B7C7C', '#d7d7d7'],
  },
  gtag: 'G-F8SDNKSNRS',
  api: 'https://kusama.webapi.subscan.io',
  domain: 'https://kusama.subscan.io',
  subdomain: ['kusama', 'localhost'],
  social: {
    telegram: 'https://t.me/kusamanetworkofficial',
    twitter: 'https://twitter.com/kusamanetwork',
    github: 'https://github.com/paritytech/polkadot/',
    price: 'https://www.coingecko.com/en/coins/kusama',
  },
  donate: 'Fzs6WWFcAuJhxAVyZa4EN2suxggjidJjV3AzJxKbRHjh2Jc',
  modules: {
    SYSTEM_ACCOUNT: false,
    VESTING: false,
    GRANDPA_VOTE: false,
    BOUNTY: true,
    NOMINATION_POOL: true,
    NOMINATE_FEATURE: true,
    PARACHAIN: true,
    POLKASSEMBLY_LINK: true,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    V2_REWARD: true,
    MULTISIG_TOOL: true,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    ASSETS_MODULE: false,
    PARATHREAD: false,
    REFERENDA_V2: true,
    FELLOWSHIP: true,
    V2_API: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    TREASURY_CHART: true,
    VALIDATOR: true,
    SS58: true,
  },
};
