import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const AcalaTestnet: Chain = {
  id: 'acala-testnet',
  nativeTokenUniqueId: 'ACA',
  name: 'Acala Mandala',
  type: 'testnet',
  theme: {
    colors: ['#173DCA', '#879BE1', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#173DCA', 6),
  },
  gtag: 'G-9Y1D522TW1',
  api: 'https://acala-testnet.webapi.subscan.io',
  domain: 'https://acala-testnet.subscan.io',
  subdomain: ['acala-testnet'],
  social: {
    telegram: 'https://t.me/acalaofficial ',
    twitter: 'https://twitter.com/AcalaNetwork ',
    github: 'https://github.com/AcalaNetwork ',
    price: '',
  },
  donate: '5FVFSCANyotNxJM4Crm1LQfsmNQSw3p8H7CRbegN7d5Ex91y',
  modules: {
    SYSTEM_ACCOUNT: false,
    VESTING: false,
    GRANDPA_VOTE: false,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: false,
    PRICE_HISTORY: false,
    PRICE_CONVERT: false,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: false,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: true,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: true,
    VALIDATOR: false,
    SS58: true,
  },
}
