import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Acala: Chain = {
  id: 'acala',
  nativeTokenUniqueId: 'ACA',
  name: 'Acala',
  type: 'mainnet',
  theme: {
    colors: ['#FF4C3B', '#FFA59D', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#FF4C3B', 6),
  },
  gtag: 'G-8661YY7LG2',
  api: 'https://acala.webapi.subscan.io',
  domain: 'https://acala.subscan.io',
  subdomain: ['acala'],
  social: {
    telegram: 'https://t.me/acalaofficial',
    twitter: 'https://twitter.com/AcalaNetwork',
    github: 'https://github.com/AcalaNetwork',
    price: 'https://www.coingecko.com/en/coins/acala',
    website: 'https://acala.network/',
    whitePaper: 'https://github.com/AcalaNetwork/Acala-white-paper',
  },
  parachain: {
    id: 2000,
    relaychain: 'polkadot',
  },
  donate: '24J9ASqUgVu7xRQDDpcFFaAH5qq3BBfUF1UDun6jJG3dwgXb',
  modules: {
    BOUNTY: true,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    EVM_NETWORK: false,
    FELLOWSHIP: false,
    GRANDPA_VOTE: true,
    MULTISIG_TOOL: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    PARATHREAD: true,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    REFERENDA_V2: false,
    SYSTEM_ACCOUNT: false,
    V2_API: false,
    V2_REWARD: false,
    VESTING: true,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    SS58: true,
    TREASURY_CHART: true,
    VALIDATOR: false,
  },
  disable: false,
}
