import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Altair: Chain = {
  id: 'altair',
  nativeTokenUniqueId: 'AIR',
  name: 'Altair',
  type: 'mainnet',
  theme: {
    colors: ['#F0BC6F', '#F7DDB6', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#F0BC6F', 6),
  },
  gtag: 'G-J38D8DE8R4',
  api: 'https://altair.webapi.subscan.io',
  domain: 'https://altair.subscan.io',
  subdomain: ['altair'],
  social: {
    telegram: 'https://t.me/centrifuge_chat ',
    twitter: 'https://twitter.com/centrifuge ',
    github: 'https://github.com/centrifuge/ ',
    price: 'https://www.coingecko.com/en/coins/altair',
  },
  donate: 'kALaKSAvNpj8akUhh9aDtrHapvJ1DZENQj2NtieKNswmwiGDs',
  modules: {
    BOUNTY: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    EVM_NETWORK: false,
    FELLOWSHIP: false,
    GRANDPA_VOTE: true,
    MULTISIG_TOOL: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    PARATHREAD: true,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    REFERENDA_V2: false,
    SYSTEM_ACCOUNT: false,
    V2_API: false,
    V2_REWARD: false,
    VESTING: true,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    SS58: true,
    TREASURY_CHART: true,
    VALIDATOR: false,
  },
}
