import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Arctic: Chain = {
  id: 'arctic',
  nativeTokenUniqueId: 'ICZ',
  name: 'ICE Arctic',
  type: 'testnet',
  theme: {
    colors: ['#4EADCF', '#A6D6E7', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#4EADCF', 6),
  },
  gtag: 'G-DL4ZWN3HC3',
  api: 'https://arctic.webapi.subscan.io',
  domain: 'https://arctic.subscan.io',
  subdomain: ['arctic'],
  social: {
    telegram: '',
    twitter: 'https://twitter.com/icenetwork_io',
    github: '',
    price: '',
  },
  donate: '5FVFSCANyotNxJM4Crm1LQfsmNQSw3p8H7CRbegN7d5Ex91y',
  modules: {
    BOUNTY: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    EVM_NETWORK: false,
    FELLOWSHIP: false,
    GRANDPA_VOTE: true,
    MULTISIG_TOOL: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    PARATHREAD: false,
    POLKASSEMBLY_LINK: false,
    PRICE: false,
    PRICE_HISTORY: false,
    PRICE_CONVERT: false,
    REFERENDA_V2: false,
    SYSTEM_ACCOUNT: false,
    V2_API: false,
    V2_REWARD: false,
    VESTING: true,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    SS58: true,
    TREASURY_CHART: true,
    VALIDATOR: false,
  },
}
