import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Basilisk: Chain = {
  id: 'basilisk',
  nativeTokenUniqueId: 'BSX',
  name: 'Basilisk',
  type: 'mainnet',
  theme: {
    colors: ['#34323C', '#99989D', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#34323C', 6),
  },
  gtag: 'G-E98K4GEHED',
  api: 'https://basilisk.webapi.subscan.io',
  domain: 'https://basilisk.subscan.io',
  subdomain: ['basilisk'],
  social: {
    telegram: 'https://t.me/bsx_fi ',
    twitter: 'https://twitter.com/bsx_finance ',
    github: 'https://github.com/galacticcouncil ',
    price: 'https://www.coingecko.com/en/coins/basilisk',
  },
  donate: 'bXk1xcqYdf5G5Az5M6UfjQHKvSvZyCmM6N72B6Wmpv1bbmG7e',
  modules: {
    SYSTEM_ACCOUNT: false,
    VESTING: true,
    GRANDPA_VOTE: true,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: true,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: true,
    VALIDATOR: false,
    SS58: true,
  },
}
