import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const BifrostKusama: Chain = {
  id: 'bifrost-kusama',
  nativeTokenUniqueId: 'BNC',
  name: 'Bifrost Kusama',
  type: 'mainnet',
  theme: {
    colors: ['#5a25f0', '#b499ff', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#5a25f0', 6),
  },
  gtag: 'G-P3H40W3HP4',
  api: 'https://bifrost-kusama.webapi.subscan.io',
  domain: 'https://bifrost-kusama.subscan.io',
  subdomain: ['bifrost-kusama'],
  social: {
    telegram: 'https://t.me/bifrost_finance ',
    twitter: 'https://twitter.com/bifrost_finance ',
    github: 'https://github.com/bifrost-finance ',
    price: 'https://www.coingecko.com/en/coins/bifrost-native-coin',
  },
  donate: 'f9W8Ufs9LQDLBnMbh69jy6aVuFrxT9PVFFhT3XXSqfgpHr9',
  modules: {
    SYSTEM_ACCOUNT: false,
    VESTING: false,
    GRANDPA_VOTE: false,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: true,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: true,
    VALIDATOR: true,
    SS58: true,
  },
}
