import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const CentrifugeParachain: Chain = {
  id: 'centrifuge-parachain',
  nativeTokenUniqueId: 'CFG',
  name: 'Centrifuge',
  type: 'mainnet',
  theme: {
    colors: ['#000000', '#7B7C7C', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#000000', 6),
  },
  gtag: '',
  api: 'https://centrifuge.webapi.subscan.io',
  domain: 'https://centrifuge.subscan.io',
  subdomain: ['centrifuge'],
  social: {
    telegram: '',
    twitter: 'https://twitter.com/centrifuge',
    github: 'https://github.com/centrifuge/centrifuge-chain',
    price: 'https://www.coingecko.com/en/coins/centrifuge',
    website: 'https://centrifuge.io/',
    whitePaper: '',
  },
  donate: '4emHtEuxg4e21wvGmfUs515KtTYgbx319TsduYpZLVWKGBu8',
  modules: {
    BOUNTY: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    EVM_NETWORK: false,
    FELLOWSHIP: false,
    GRANDPA_VOTE: true,
    MULTISIG_TOOL: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    PARATHREAD: true,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    REFERENDA_V2: false,
    SYSTEM_ACCOUNT: false,
    V2_API: false,
    V2_REWARD: false,
    VESTING: true,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    SS58: true,
    TREASURY_CHART: false,
    VALIDATOR: false,
  },
  disable: false,
}
