import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Centrifuge: Chain = {
  id: 'centrifuge',
  nativeTokenUniqueId: 'CFG',
  name: 'Centrifuge Legacy',
  type: 'mainnet',
  theme: {
    colors: ['#000000', '#7B7C7C', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#000000', 6),
  },
  gtag: 'G-V9HDLXZ406',
  api: 'https://centrifuge-standalone-history.webapi.subscan.io',
  domain: 'https://centrifuge-standalone-history.subscan.io',
  subdomain: ['centrifuge-standalone-history'],
  social: {
    telegram: ' ',
    twitter: 'https://twitter.com/centrifuge ',
    github: 'https://github.com/centrifuge/centrifuge-chain ',
    price: '',
  },
  donate: '4emHtEuxg4e21wvGmfUs515KtTYgbx319TsduYpZLVWKGBu8',
  modules: {
    SYSTEM_ACCOUNT: false,
    VESTING: true,
    GRANDPA_VOTE: true,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: false,
    PRICE_HISTORY: false,
    PRICE_CONVERT: false,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: false,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: true,
    VALIDATOR: true,
    SS58: true,
  },
}
