import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Chainx: Chain = {
  id: 'chainx',
  nativeTokenUniqueId: 'PCX',
  name: 'ChainX',
  type: 'mainnet',
  theme: {
    colors: ['#2E2E2E', '#929393', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#2E2E2E', 6),
  },
  gtag: 'G-6WG30F4WTZ',
  api: 'https://chainx.webapi.subscan.io',
  domain: 'https://chainx.subscan.io',
  subdomain: ['chainx'],
  social: {
    telegram: 'https://t.me/chainx_org ',
    twitter: 'https://twitter.com/chainx_org ',
    github: 'https://github.com/chainx-org/chainx ',
    price: 'https://www.coingecko.com/en/coins/chainx',
  },
  donate: '5T4ZxBFBkPdqGR9z1vX46DCj4Lh33R5AezJgq1xy3LGDWYBp',
  modules: {
    SYSTEM_ACCOUNT: false,
    VESTING: false,
    GRANDPA_VOTE: false,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: false,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: false,
    VALIDATOR: true,
    SS58: true,
  },
}
