import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const CloverTestnet: Chain = {
  id: 'clover-testnet',
  nativeTokenUniqueId: 'CLV',
  name: 'Clover Testnet',
  type: 'testnet',
  theme: {
    colors: ['#25E5DA', '#92F2EC', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#25E5DA', 6),
  },
  gtag: 'G-C466PTP61F',
  api: 'https://clover-testnet.webapi.subscan.io',
  domain: 'https://clover-testnet.subscan.io',
  subdomain: ['clover-testnet'],
  social: {
    telegram: 'https://t.me/clover_en/ ',
    twitter: 'https://twitter.com/clover_finance ',
    github: 'https://github.com/clover-network ',
    price: '',
  },
  donate: '5FVFSCANyotNxJM4Crm1LQfsmNQSw3p8H7CRbegN7d5Ex91y',
  modules: {
    SYSTEM_ACCOUNT: false,
    VESTING: true,
    GRANDPA_VOTE: true,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: false,
    PRICE_HISTORY: false,
    PRICE_CONVERT: false,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: false,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: true,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: false,
    VALIDATOR: true,
    SS58: true,
  },
}
