import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Composable: Chain = {
  id: 'composable',
  nativeTokenUniqueId: 'LAYR',
  name: 'Composable',
  type: 'mainnet',
  theme: {
    colors: ['#6A32DF', '#B195EC', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#6A32DF', 6),
  },
  gtag: 'G-EVLDB62B3F',
  api: 'https://composable.webapi.subscan.io',
  domain: 'https://composable.subscan.io',
  subdomain: ['composable'],
  social: {
    telegram: '',
    twitter: 'https://twitter.com/ComposableFin',
    github: 'https://github.com/ComposableFi/',
    price: '',
    website: 'https://www.composable.finance/',
    whitePaper: '',
  },
  parachain: {
    id: 2019,
    relaychain: 'polkadot',
  },
  donate: '5wzsF8xCfr1U3iBJYavAyiXrHmQWKLDmbh5LuSBUMcEevAft',
  modules: {
    BOUNTY: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    EVM_NETWORK: false,
    FELLOWSHIP: false,
    GRANDPA_VOTE: false,
    MULTISIG_TOOL: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    PARATHREAD: true,
    POLKASSEMBLY_LINK: false,
    PRICE: false,
    PRICE_HISTORY: false,
    PRICE_CONVERT: false,
    REFERENDA_V2: false,
    SYSTEM_ACCOUNT: false,
    V2_API: false,
    V2_REWARD: false,
    VESTING: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    SS58: true,
    TREASURY_CHART: true,
    VALIDATOR: false,
  },
  disable: false,
}
