import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const CrabParachain: Chain = {
  id: 'crab-parachain',
  nativeTokenUniqueId: 'CRAB',
  name: 'Crab2',
  type: 'mainnet',
  theme: {
    colors: ['#512DBC', '#AE94EC', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#512DBC', 6),
  },
  gtag: 'G-MD05D8X1QZ',
  api: 'https://crab.webapi.subscan.io',
  domain: 'https://crab.subscan.io',
  subdomain: ['crab'],
  social: {
    telegram: 'https://t.me/DarwiniaNetwork',
    twitter: 'https://twitter.com/DarwiniaNetwork',
    github: 'https://github.com/darwinia-network',
    price: '',
  },
  donate: '0x9c0fEf6b48Cb0B16EDc72a61d9503A78782c19e2',
  modules: {
    BOUNTY: false,
    CONTRACT: true,
    CONTRACT_SOURCIFY: true,
    ETH_ADDRESS: true,
    EVM: true,
    EVM_NETWORK: true,
    FELLOWSHIP: false,
    GRANDPA_VOTE: true,
    MULTISIG_TOOL: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    PARATHREAD: true,
    POLKASSEMBLY_LINK: false,
    PRICE: false,
    PRICE_HISTORY: false,
    PRICE_CONVERT: false,
    REFERENDA_V2: false,
    SYSTEM_ACCOUNT: true,
    V2_API: false,
    V2_REWARD: false,
    VESTING: true,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    SS58: false,
    TREASURY_CHART: true,
    VALIDATOR: false,
  },
}
