import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Crab: Chain = {
  id: 'crab',
  nativeTokenUniqueId: 'CRAB',
  name: 'Darwinia Crab',
  type: 'mainnet',
  theme: {
    colors: ['#512DBC', '#AE94EC', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#512DBC', 6),
  },
  gtag: 'G-CP7HRJLKYD',
  api: 'https://crab1.webapi.subscan.io',
  domain: 'https://crab1.subscan.io',
  subdomain: ['crab1'],
  social: {
    telegram: 'https://t.me/DarwiniaNetwork ',
    twitter: 'https://twitter.com/DarwiniaNetwork ',
    github: 'https://github.com/darwinia-network ',
    price: '',
  },
  donate: '5FVFSCANyotNxJM4Crm1LQfsmNQSw3p8H7CRbegN7d5Ex91y',
  modules: {
    SYSTEM_ACCOUNT: true,
    VESTING: true,
    GRANDPA_VOTE: true,
    BOUNTY: true,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: true,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: false,
    PRICE_HISTORY: false,
    PRICE_CONVERT: false,
    V2_REWARD: false,
    MULTISIG_TOOL: true,
    EVM_NETWORK: false,
    CONTRACT: true,
    CONTRACT_SOURCIFY: true,
    ETH_ADDRESS: false,
    EVM: true,
    PARATHREAD: false,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: true,
    VALIDATOR: true,
    SS58: true,
  },
}
