import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Crust: Chain = {
  id: 'crust',
  nativeTokenUniqueId: 'CRU',
  name: 'Crust',
  type: 'mainnet',
  theme: {
    colors: ['#ED6E2D', '#F3B393', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#ED6E2D', 6),
  },
  gtag: 'G-VP80VFEH8J',
  api: 'https://crust.webapi.subscan.io',
  domain: 'https://crust.subscan.io',
  subdomain: ['crust'],
  social: {
    telegram: 'https://t.me/CrustNetwork ',
    twitter: 'https://twitter.com/CrustNetwork ',
    github: 'https://github.com/crustio ',
    price: 'https://www.coingecko.com/en/coins/crust-network',
  },
  donate: 'cTKmBRbJ93JvP3WKTUP5VBC97WVMsgBUbfCWgUZ8WZBuSty4u',
  modules: {
    SYSTEM_ACCOUNT: false,
    VESTING: false,
    GRANDPA_VOTE: false,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: false,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: true,
    VALIDATOR: true,
    SS58: true,
  },
}
