import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Darwinia: Chain = {
  id: 'darwinia',
  nativeTokenUniqueId: 'RING',
  name: 'Darwinia',
  type: 'mainnet',
  theme: {
    colors: ['#EA3382', '#F499C0', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#EA3382', 6),
  },
  gtag: 'G-45ZXR89JPN',
  api: 'https://darwinia1.webapi.subscan.io',
  domain: 'https://darwinia1.subscan.io',
  subdomain: ['darwinia1'],
  social: {
    telegram: 'https://t.me/DarwiniaNetwork ',
    twitter: 'https://twitter.com/DarwiniaNetwork ',
    github: 'https://github.com/darwinia-network ',
    price: 'https://www.coingecko.com/en/coins/darwinia-network-native-token',
  },
  donate: '2rbREPAhkptwCtdvU5eSGnHgFiyPcehdkXuGqFF916oYCJ7s',
  modules: {
    SYSTEM_ACCOUNT: true,
    VESTING: true,
    GRANDPA_VOTE: true,
    BOUNTY: true,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: true,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    V2_REWARD: false,
    MULTISIG_TOOL: true,
    EVM_NETWORK: false,
    CONTRACT: true,
    CONTRACT_SOURCIFY: true,
    ETH_ADDRESS: false,
    EVM: true,
    PARATHREAD: false,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: true,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: true,
    VALIDATOR: true,
    SS58: true,
  },
}
