import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const DatahighwayTanganika: Chain = {
  id: 'datahighway-tanganika',
  nativeTokenUniqueId: 'DHX',
  name: 'Datahighway Tanganika',
  type: 'mainnet',
  theme: {
    colors: ['#4765EA', '#A3B2F4', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#4765EA', 6),
  },
  gtag: 'G-WWWF7HJZ92',
  api: 'https://datahighway.webapi.subscan.io',
  domain: 'https://datahighway.subscan.io',
  subdomain: ['datahighway'],
  social: {
    telegram: ' ',
    twitter: 'https://twitter.com/DataHighway_DHX ',
    github: ' ',
    price: 'https://www.coingecko.com/en/coins/datahighway',
  },
  donate: '4MQK7GHkXC1qYmht44qnwJH3x17oSQ9SaeDF4VtewvirREuw',
  modules: {
    SYSTEM_ACCOUNT: false,
    VESTING: false,
    GRANDPA_VOTE: false,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: true,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: true,
    VALIDATOR: false,
    SS58: true,
  },
}
