import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Dbc: Chain = {
  id: 'dbc',
  nativeTokenUniqueId: 'DBC',
  name: 'DeepBrain Chain',
  type: 'mainnet',
  theme: {
    colors: ['#0D1C3B', '#00E6F5', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#0D1C3B', 6),
  },
  gtag: 'G-N68YNP9RP7',
  api: 'https://dbc.webapi.subscan.io',
  domain: 'https://dbc.subscan.io',
  subdomain: ['dbc'],
  social: {
    telegram: 'https://t.me/deepbrainchainglobal',
    twitter: 'https://twitter.com/DeepBrainChain',
    github: 'https://github.com/DeepBrainChain',
    price: 'https://www.coingecko.com/en/coins/deepbrain-chain',
  },
  donate: '5FVFSCANyotNxJM4Crm1LQfsmNQSw3p8H7CRbegN7d5Ex91y',
  modules: {
    BOUNTY: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    EVM_NETWORK: false,
    FELLOWSHIP: false,
    GRANDPA_VOTE: true,
    MULTISIG_TOOL: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    PARATHREAD: false,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    REFERENDA_V2: false,
    SYSTEM_ACCOUNT: false,
    V2_API: false,
    V2_REWARD: false,
    VESTING: true,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    SS58: true,
    TREASURY_CHART: true,
    VALIDATOR: true,
  },
}
