import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Dock: Chain = {
  id: 'dock',
  nativeTokenUniqueId: 'DOCK',
  name: 'Dock',
  type: 'mainnet',
  theme: {
    colors: ['#1B83E3', '#8DC1F1', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#1B83E3', 6),
  },
  gtag: 'G-FF7MVPJZR6',
  api: 'https://dock.webapi.subscan.io',
  domain: 'https://dock.subscan.io',
  subdomain: ['dock'],
  social: {
    telegram: 'https://t.me/dockio ',
    twitter: 'https://twitter.com/docknetwork ',
    github: 'https://github.com/docknetwork ',
    price: 'https://www.coingecko.com/en/coins/dock',
  },
  donate: '3Fk4GMLKHzPqq8Fn6DAXnPMNqfYZqPDiWJ7oHypLrXBVKcA1',
  modules: {
    SYSTEM_ACCOUNT: false,
    VESTING: false,
    GRANDPA_VOTE: false,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: false,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: true,
    VALIDATOR: true,
    SS58: true,
  },
}
