import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Dolphin: Chain = {
  id: 'dolphin',
  nativeTokenUniqueId: 'DOL',
  name: 'Dolphin',
  type: 'testnet',
  theme: {
    colors: ['#1D66A6', '#8BAFCF', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#1D66A6', 6),
  },
  gtag: 'G-DBPWV3MW0K',
  api: 'https://dolphin.webapi.subscan.io',
  domain: 'https://dolphin.subscan.io',
  subdomain: ['dolphin'],
  social: {
    telegram: 'https://t.me/mantanetworkofficial ',
    twitter: 'https://twitter.com/mantanetwork ',
    github: 'https://github.com/Manta-Network ',
    price: '',
  },
  donate: '5FVFSCANyotNxJM4Crm1LQfsmNQSw3p8H7CRbegN7d5Ex91y',
  modules: {
    SYSTEM_ACCOUNT: false,
    VESTING: false,
    GRANDPA_VOTE: false,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: false,
    PRICE_HISTORY: false,
    PRICE_CONVERT: false,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: true,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: true,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: false,
    VALIDATOR: false,
    SS58: true,
  },
}
