import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Edgeware: Chain = {
  id: 'edgeware',
  nativeTokenUniqueId: 'EDG',
  name: 'Edgeware',
  type: 'mainnet',
  theme: {
    colors: ['#151515', '#525252', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#151515', 6),
  },
  gtag: 'G-T5XNJ8357H',
  api: 'https://edgeware.webapi.subscan.io',
  domain: 'https://edgeware.subscan.io',
  subdomain: ['edgeware'],
  social: {
    telegram: 'https://t.me/heyedgeware ',
    twitter: 'https://twitter.com/heyedgeware ',
    github: 'https://github.com/hicommonwealth ',
    price: 'https://www.coingecko.com/en/coins/edgeware',
  },
  donate: 'kwAPUDGXdGwVFBpWDyB7sN19PQA1dmugBoq4jApuhGB6sAd',
  modules: {
    BOUNTY: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    EVM_NETWORK: false,
    FELLOWSHIP: false,
    GRANDPA_VOTE: true,
    MULTISIG_TOOL: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    PARATHREAD: false,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    REFERENDA_V2: false,
    SYSTEM_ACCOUNT: false,
    V2_API: false,
    V2_REWARD: false,
    VESTING: true,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    SS58: true,
    TREASURY_CHART: true,
    VALIDATOR: true,
  },
}
