import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const EfinityParachainArchive: Chain = {
  id: 'efinity-parachain-archive',
  nativeTokenUniqueId: 'EFI',
  name: 'Efinity Archive',
  type: 'mainnet',
  theme: {
    colors: ['#496ddb', '#a4b6ed', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#496ddb', 6),
  },
  gtag: '',
  api: 'https://efinity-parachain-archive.webapi.subscan.io',
  domain: 'https://efinity-parachain-archive.subscan.io',
  subdomain: ['efinity-parachain-archive'],
  social: {
    telegram: 'https://t.me/enjin',
    twitter: 'https://twitter.com/efinityio',
    github: '',
    price: 'https://www.coingecko.com/en/coins/efinity-token',
    website: 'https://enjin.io/products/efinity',
    whitePaper: '',
  },
  parachain: {
    id: 2021,
    relaychain: 'polkadot',
  },
  donate: 'efSa9KSVpWsudasm6Rzdz2FcjMWyS9VxuruqGSAu757PYFbMp',
  modules: {
    BOUNTY: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    EVM_NETWORK: false,
    FELLOWSHIP: false,
    GRANDPA_VOTE: true,
    MULTISIG_TOOL: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    PARATHREAD: true,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    REFERENDA_V2: false,
    SYSTEM_ACCOUNT: false,
    V2_API: false,
    V2_REWARD: false,
    VESTING: true,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    SS58: true,
    TREASURY_CHART: true,
    VALIDATOR: false,
  },
}
