import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Efinity: Chain = {
  id: 'efinity',
  nativeTokenUniqueId: 'EFI',
  name: 'Efinity',
  type: 'mainnet',
  theme: {
    colors: ['#496ddb', '#a4b6ed', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#496ddb', 6),
  },
  gtag: '',
  api: 'https://efinity.webapi.subscan.io',
  domain: 'https://efinity.subscan.io',
  subdomain: ['efinity'],
  social: {
    telegram: 'https://t.me/enjin ',
    twitter: 'https://twitter.com/efinityio ',
    github: ' ',
    price: 'https://www.coingecko.com/en/coins/efinity-token',
  },
  donate: 'efSa9KSVpWsudasm6Rzdz2FcjMWyS9VxuruqGSAu757PYFbMp',
  modules: {
    BOUNTY: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    EVM_NETWORK: false,
    FELLOWSHIP: false,
    GRANDPA_VOTE: true,
    MULTISIG_TOOL: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    PARATHREAD: false,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    REFERENDA_V2: false,
    SYSTEM_ACCOUNT: false,
    V2_API: false,
    V2_REWARD: false,
    VESTING: true,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    SS58: true,
    TREASURY_CHART: true,
    VALIDATOR: false,
  },
}
