import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Encointer: Chain = {
  id: 'encointer',
  nativeTokenUniqueId: 'KSM',
  name: 'Encointer',
  type: 'mainnet',
  theme: {
    colors: ['#346ED6', '#99B6EA', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#346ED6', 6),
  },
  gtag: 'G-W83S770PC3',
  api: 'https://encointer.webapi.subscan.io',
  domain: 'https://encointer.subscan.io',
  subdomain: ['encointer'],
  social: {
    telegram: '',
    twitter: 'https://twitter.com/encointer',
    github: '',
    price: 'https://www.coingecko.com/en/coins/kusama',
    website: 'https://encointer.org/',
    whitePaper: '',
  },
  parachain: {
    id: 1001,
    relaychain: 'kusama',
  },
  donate: '5FVFSCANyotNxJM4Crm1LQfsmNQSw3p8H7CRbegN7d5Ex91y',
  modules: {
    BOUNTY: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    EVM_NETWORK: false,
    FELLOWSHIP: false,
    GRANDPA_VOTE: false,
    MULTISIG_TOOL: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    PARATHREAD: true,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    REFERENDA_V2: false,
    SYSTEM_ACCOUNT: false,
    V2_API: false,
    V2_REWARD: false,
    VESTING: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    SS58: true,
    TREASURY_CHART: true,
    VALIDATOR: false,
  },
  disable: false,
}
