import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Heiko: Chain = {
  id: 'heiko',
  nativeTokenUniqueId: 'HKO',
  name: 'Parallel Heiko',
  type: 'mainnet',
  theme: {
    colors: ['#0BD0FE', '#85E7FE', '#e6e6e6'],
    gradient: generateGradientColor('#d7d7d7', '#0BD0FE', 6),
  },
  gtag: 'G-R25JXJ3DXV',
  api: 'https://parallel-heiko.webapi.subscan.io',
  domain: 'https://parallel-heiko.subscan.io',
  subdomain: ['parallel-heiko'],
  social: {
    telegram: 'https://t.me/parallelfi_community',
    twitter: 'https://twitter.com/ParallelFi',
    github: 'https://github.com/parallel-finance',
    price: '',
    website: 'https://parallel.fi/',
    whitePaper: '',
  },
  parachain: {
    id: 2085,
    relaychain: 'kusama',
  },
  donate: 'hJJchKKyVJbo8roXn1eNNWo3jUt3vEGcJqtYQyJANR6LZQhHS',
  modules: {
    BOUNTY: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    EVM_NETWORK: false,
    FELLOWSHIP: false,
    GRANDPA_VOTE: true,
    MULTISIG_TOOL: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    PARATHREAD: true,
    POLKASSEMBLY_LINK: false,
    PRICE: false,
    PRICE_HISTORY: false,
    PRICE_CONVERT: false,
    REFERENDA_V2: false,
    SYSTEM_ACCOUNT: true,
    V2_API: false,
    V2_REWARD: false,
    VESTING: true,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    SS58: true,
    TREASURY_CHART: true,
    VALIDATOR: false,
  },
  disable: false,
}
