import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Humanode: Chain = {
  id: 'humanode',
  nativeTokenUniqueId: 'HMND',
  name: 'Humanode',
  type: 'mainnet',
  theme: {
    colors: ['#ffad6c', '#FFD6B5', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#ffad6c', 6),
  },
  gtag: 'G-E1DL25YMJ5',
  api: 'https://humanode.webapi.subscan.io',
  domain: 'https://humanode.subscan.io',
  subdomain: ['humanode'],
  social: {
    telegram: 'https://t.me/humanode ',
    twitter: 'https://twitter.com/humanode_io ',
    github: 'https://github.com/humanode-network ',
    price: 'https://www.coingecko.com/en/coins/humanode',
  },
  donate: 'hmqtkf9QmNuBjy1BozbAvjWT1roX5NrPxuVSemwfUD6T95prd',
  modules: {
    SYSTEM_ACCOUNT: true,
    VESTING: true,
    GRANDPA_VOTE: true,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: false,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: false,
    VALIDATOR: false,
    SS58: true,
  },
}
