import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Hydradx: Chain = {
  id: 'hydradx',
  nativeTokenUniqueId: 'HDX',
  name: 'HydraDX',
  type: 'mainnet',
  theme: {
    colors: ['#0D106A', '#8687B4', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#0D106A', 6),
  },
  gtag: 'G-9MF167LCL0',
  api: 'https://hydradx.webapi.subscan.io',
  domain: 'https://hydradx.subscan.io',
  subdomain: ['hydradx'],
  social: {
    telegram: 'https://t.me/hydradx ',
    twitter: 'https://twitter.com/hydra_dx ',
    github: 'https://github.com/galacticcouncil ',
    price: 'https://www.coingecko.com/en/coins/hydradx',
  },
  donate: '7M26s2Xr3vFeEXqoE3EWGLFoLZQd5u34ErqBX1BgqaZUrrBz',
  modules: {
    SYSTEM_ACCOUNT: false,
    VESTING: true,
    GRANDPA_VOTE: true,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: true,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: true,
    VALIDATOR: false,
    SS58: true,
  },
}
