import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Interlay: Chain = {
  id: 'interlay',
  nativeTokenUniqueId: 'INTR',
  name: 'Interlay',
  type: 'mainnet',
  theme: {
    colors: ['#041333', '#818999', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#041333', 6),
  },
  gtag: 'G-FG91XBDBHY',
  api: 'https://interlay.webapi.subscan.io',
  domain: 'https://interlay.subscan.io',
  subdomain: ['interlay'],
  social: {
    telegram: 'https://t.me/interlay_community',
    twitter: 'https://twitter.com/interlayHQ',
    github: 'https://github.com/interlay',
    price: 'https://www.coingecko.com/en/coins/interlay',
    website: 'https://interlay.io/',
    whitePaper: 'https://docs.interlay.io/#/',
  },
  parachain: {
    id: 2032,
    relaychain: 'polkadot',
  },
  donate: 'wdAvRiVVkbGbTQbDc31o9qZbBCLpUFMpTa9bj1pSWyLgttyZM',
  modules: {
    BOUNTY: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    EVM_NETWORK: false,
    FELLOWSHIP: false,
    GRANDPA_VOTE: true,
    MULTISIG_TOOL: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    PARATHREAD: true,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    REFERENDA_V2: false,
    SYSTEM_ACCOUNT: true,
    V2_API: false,
    V2_REWARD: false,
    VESTING: true,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    SS58: true,
    TREASURY_CHART: true,
    VALIDATOR: false,
  },
  disable: false,
}
