import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Integritee: Chain = {
  id: 'integritee',
  nativeTokenUniqueId: 'TEER',
  name: 'IntegriTEE',
  type: 'mainnet',
  theme: {
    colors: ['#01055F', '#8082AF', '#e6e6e6'],
    gradient: generateGradientColor('#d7d7d7', '#01055F', 6),
  },
  gtag: 'G-R30DEX3S7E',
  api: 'https://integritee.webapi.subscan.io',
  domain: 'https://integritee.subscan.io',
  subdomain: ['integritee'],
  social: {
    telegram: 'https://t.me/Integritee_Official ',
    twitter: 'https://twitter.com/integri_t_e_e ',
    github: 'https://github.com/integritee-network ',
    price: 'https://www.coingecko.com/en/coins/integritee',
  },
  donate: '2Mf7wRTgqNXJRbcbwRFKPGxZ2JFvLjZ2oq8ckq2dgpq6ngha',
  modules: {
    SYSTEM_ACCOUNT: false,
    VESTING: true,
    GRANDPA_VOTE: true,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: true,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: false,
    VALIDATOR: false,
    SS58: true,
  },
}
