import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Interlay: Chain = {
  id: 'interlay',
  nativeTokenUniqueId: 'INTR',
  name: 'Interlay',
  type: 'mainnet',
  theme: {
    colors: ['#041333', '#818999', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#041333', 6),
  },
  gtag: 'G-FG91XBDBHY',
  api: 'https://interlay.webapi.subscan.io',
  domain: 'https://interlay.subscan.io',
  subdomain: ['interlay'],
  social: {
    telegram: 'https://t.me/interlay_community ',
    twitter: 'https://twitter.com/interlayHQ ',
    github: 'https://github.com/interlay ',
    price: 'https://www.coingecko.com/en/coins/interlay',
  },
  donate: 'wdAvRiVVkbGbTQbDc31o9qZbBCLpUFMpTa9bj1pSWyLgttyZM',
  modules: {
    SYSTEM_ACCOUNT: true,
    VESTING: true,
    GRANDPA_VOTE: true,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: true,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: true,
    VALIDATOR: false,
    SS58: true,
  },
}
