import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const KaruraRococo: Chain = {
  id: 'karura-rococo',
  nativeTokenUniqueId: 'KAR',
  name: 'Karura-rococo',
  type: 'testnet',
  theme: {
    colors: ['#FF4D3B', '#FFA69D', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#FF4D3B', 6),
  },
  gtag: '',
  api: 'https://karura-rococo.webapi.subscan.io',
  domain: 'https://karura-rococo.subscan.io',
  subdomain: ['karura-rococo'],
  social: {
    telegram: ' ',
    twitter: ' ',
    github: 'https://github.com/AcalaNetwork ',
    price: 'https://www.coingecko.com/en/coins/karura',
  },
  donate: 'ripeTkfuv9feJbHQkrCVmdRnsYT4pQRs8MxgQp8NYrfP6o2',
  modules: {
    SYSTEM_ACCOUNT: false,
    VESTING: true,
    GRANDPA_VOTE: true,
    BOUNTY: true,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: false,
    PRICE_CONVERT: false,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: true,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: true,
    VALIDATOR: false,
    SS58: true,
  },
}
