import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Kilt: Chain = {
  id: 'kilt',
  nativeTokenUniqueId: 'PILT',
  name: 'KILT Peregrine',
  type: 'testnet',
  theme: {
    colors: ['#8C145A', '#C286A9', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#8C145A', 6),
  },
  gtag: 'G-XJTDS989XD',
  api: 'https://kilt-testnet.webapi.subscan.io',
  domain: 'https://kilt-testnet.subscan.io',
  subdomain: ['kilt-testnet'],
  social: {
    telegram: 'https://t.me/KILTProtocolChat ',
    twitter: 'https://twitter.com/Kiltprotocol ',
    github: 'https://github.com/KILTprotocol ',
    price: '',
  },
  donate: '4rLcQDzmSePUL4jCajEupocBBRqGiKJ3XLyu8v7AGChHpa9u',
  modules: {
    SYSTEM_ACCOUNT: false,
    VESTING: true,
    GRANDPA_VOTE: true,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: false,
    PRICE_HISTORY: false,
    PRICE_CONVERT: false,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: false,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: true,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: true,
    VALIDATOR: false,
    SS58: true,
  },
}
