import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const KiltSpiritnet: Chain = {
  id: 'kilt-spiritnet',
  nativeTokenUniqueId: 'KILT',
  name: 'KILT Spiritnet',
  type: 'mainnet',
  theme: {
    colors: ['#8C145A', '#C286A9', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#8C145A', 6),
  },
  gtag: 'G-650RPH2L01',
  api: 'https://spiritnet.webapi.subscan.io',
  domain: 'https://spiritnet.subscan.io',
  subdomain: ['spiritnet'],
  social: {
    telegram: 'https://t.me/KILTProtocolChat ',
    twitter: 'https://twitter.com/Kiltprotocol ',
    github: 'https://github.com/KILTprotocol ',
    price: 'https://www.coingecko.com/en/coins/kilt-protocol',
  },
  donate: '4rLcQDzmSePUL4jCajEupocBBRqGiKJ3XLyu8v7AGChHpa9u',
  modules: {
    SYSTEM_ACCOUNT: false,
    VESTING: true,
    GRANDPA_VOTE: true,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: true,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: false,
    VALIDATOR: false,
    SS58: true,
  },
}
