import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Kulupu: Chain = {
  id: 'kulupu',
  nativeTokenUniqueId: 'KLP',
  name: 'Kulupu',
  type: 'mainnet',
  theme: {
    colors: ['#18B06B', '#71CDA4', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#18B06B', 6),
  },
  gtag: 'G-N20B8D58HC',
  api: 'https://kulupu.webapi.subscan.io',
  domain: 'https://kulupu.subscan.io',
  subdomain: ['kulupu'],
  social: {
    telegram: ' ',
    twitter: 'https://twitter.com/home ',
    github: 'https://github.com/kulupu/kulupu ',
    price: 'https://www.coingecko.com/en/coins/kulupu',
  },
  donate: '2f26iQ5tzF9Utmpzf1tPWykpxkgoWHSbNeo1bsxY5PcZdbZb',
  modules: {
    SYSTEM_ACCOUNT: false,
    VESTING: true,
    GRANDPA_VOTE: true,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: false,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: true,
    VALIDATOR: false,
    SS58: true,
  },
}
