import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Kusama: Chain = {
  id: 'kusama',
  nativeTokenUniqueId: 'KSM',
  name: 'Kusama',
  type: 'mainnet',
  theme: {
    colors: ['#000000', '#7B7C7C', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#000000', 6),
  },
  gtag: 'G-F8SDNKSNRS',
  api: 'https://kusama.webapi.subscan.io',
  domain: 'https://kusama.subscan.io',
  subdomain: ['kusama'],
  social: {
    telegram: 'https://t.me/kusamanetworkofficial ',
    twitter: 'https://twitter.com/kusamanetwork ',
    github: 'https://github.com/paritytech/polkadot/ ',
    price: 'https://www.coingecko.com/en/coins/kusama',
  },
  donate: 'Fzs6WWFcAuJhxAVyZa4EN2suxggjidJjV3AzJxKbRHjh2Jc',
  modules: {
    SYSTEM_ACCOUNT: false,
    VESTING: true,
    GRANDPA_VOTE: true,
    BOUNTY: true,
    NOMINATION_POOL: true,
    NOMINATE_FEATURE: true,
    PARACHAIN: true,
    POLKASSEMBLY_LINK: true,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    V2_REWARD: true,
    MULTISIG_TOOL: true,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: false,
    REFERENDA_V2: true,
    FELLOWSHIP: true,
    V2_API: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: true,
    VALIDATOR: true,
    SS58: true,
  },
}
