import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Mangatax: Chain = {
  id: 'mangatax',
  nativeTokenUniqueId: 'MGX',
  name: 'Mangata',
  type: 'mainnet',
  theme: {
    colors: ['#14ABB9', '#89D5DC', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#14ABB9', 6),
  },
  gtag: 'G-NW65V3W0DJ',
  api: 'https://mangatax.webapi.subscan.io',
  domain: 'https://mangatax.subscan.io',
  subdomain: ['mangatax'],
  social: {
    telegram: 'https://t.me/mgtfi ',
    twitter: 'https://twitter.com/MangataFinance ',
    github: 'https://github.com/mangata-finance ',
    price: '',
  },
  donate: '5FVFSCANyotNxJM4Crm1LQfsmNQSw3p8H7CRbegN7d5Ex91y',
  modules: {
    SYSTEM_ACCOUNT: false,
    VESTING: false,
    GRANDPA_VOTE: false,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: false,
    PRICE_HISTORY: false,
    PRICE_CONVERT: false,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: true,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: true,
    VALIDATOR: false,
    SS58: true,
  },
}
