import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Moonbase: Chain = {
  id: 'moonbase',
  nativeTokenUniqueId: 'DEV',
  name: 'Moonbase',
  type: 'testnet',
  theme: {
    colors: ['#180C24', '#87828E', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#180C24', 6),
  },
  gtag: 'G-733HFBDEEC',
  api: 'https://moonbase.webapi.subscan.io',
  domain: 'https://moonbase.subscan.io',
  subdomain: ['moonbase'],
  social: {
    telegram: 'https://t.me/Moonbeam_Official ',
    twitter: 'https://twitter.com/moonbeamnetwork ',
    github: 'https://github.com/PureStake/moonbeam ',
    price: '',
  },
  donate: '0x9c0fEf6b48Cb0B16EDc72a61d9503A78782c19e2',
  modules: {
    BOUNTY: false,
    CONTRACT: true,
    CONTRACT_SOURCIFY: true,
    ETH_ADDRESS: true,
    EVM: true,
    EVM_NETWORK: true,
    FELLOWSHIP: false,
    GRANDPA_VOTE: false,
    MULTISIG_TOOL: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    PARATHREAD: false,
    POLKASSEMBLY_LINK: false,
    PRICE: false,
    PRICE_HISTORY: false,
    PRICE_CONVERT: false,
    REFERENDA_V2: true,
    SYSTEM_ACCOUNT: false,
    V2_API: true,
    V2_REWARD: false,
    VESTING: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    SS58: false,
    TREASURY_CHART: false,
    VALIDATOR: true,
  },
}
