import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const OrigintrailTestnet: Chain = {
  id: 'origintrail-testnet',
  nativeTokenUniqueId: 'OTP',
  name: 'OriginTrail Testnet',
  type: 'testnet',
  theme: {
    colors: ['#2B2C2D', '#7C7C7C', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#2B2C2D', 6),
  },
  gtag: 'G-71G8G4SCBH',
  api: 'https://origintrail-testnet.webapi.subscan.io',
  domain: 'https://origintrail-testnet.subscan.io',
  subdomain: ['origintrail-testnet'],
  social: {
    telegram: 'https://t.me/OriginTrail',
    twitter: 'https://twitter.com/origin_trail',
    github: '',
    price: '',
    website: 'https://origintrail.io/',
    whitePaper: 'https://parachain.origintrail.io/whitepaper',
  },
  donate: 'gJqAkRt7Fw22UtzWaJyeh1jryDPgYchvWC7SnbbiwiZqhJhX2',
  modules: {
    BOUNTY: false,
    CONTRACT: true,
    CONTRACT_SOURCIFY: true,
    ETH_ADDRESS: true,
    EVM: true,
    EVM_NETWORK: false,
    FELLOWSHIP: false,
    GRANDPA_VOTE: true,
    MULTISIG_TOOL: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    PARATHREAD: true,
    POLKASSEMBLY_LINK: false,
    PRICE: false,
    PRICE_HISTORY: false,
    PRICE_CONVERT: false,
    REFERENDA_V2: false,
    SYSTEM_ACCOUNT: false,
    V2_API: false,
    V2_REWARD: false,
    VESTING: true,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    SS58: true,
    TREASURY_CHART: true,
    VALIDATOR: false,
  },
}
