import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Pangolin: Chain = {
  id: 'pangolin',
  nativeTokenUniqueId: 'PRING',
  name: 'Pangolin',
  type: 'testnet',
  theme: {
    colors: ['#512DBC', '#AE94EC', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#512DBC', 6),
  },
  gtag: 'G-T51J9D88Y2',
  api: 'https://pangolin.webapi.subscan.io',
  domain: 'https://pangolin.subscan.io',
  subdomain: ['pangolin'],
  social: {
    telegram: 'https://t.me/DarwiniaNetwork',
    twitter: 'https://twitter.com/DarwiniaNetwork',
    github: 'https://github.com/darwinia-network',
    price: '',
    website: 'https://darwinia.network/',
    whitePaper: '',
  },
  donate: '2rbREPAhkptwCtdvU5eSGnHgFiyPcehdkXuGqFF916oYCJ7s',
  modules: {
    BOUNTY: true,
    CONTRACT: true,
    CONTRACT_SOURCIFY: true,
    ETH_ADDRESS: false,
    EVM: true,
    EVM_NETWORK: false,
    FELLOWSHIP: false,
    GRANDPA_VOTE: true,
    MULTISIG_TOOL: true,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    PARATHREAD: false,
    POLKASSEMBLY_LINK: false,
    PRICE: false,
    PRICE_HISTORY: false,
    PRICE_CONVERT: false,
    REFERENDA_V2: false,
    SYSTEM_ACCOUNT: true,
    V2_API: true,
    V2_REWARD: false,
    VESTING: true,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    SS58: true,
    TREASURY_CHART: true,
    VALIDATOR: true,
  },
  disable: true,
}
