import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Polkadex: Chain = {
  id: 'polkadex',
  nativeTokenUniqueId: 'PDEX',
  name: 'Polkadex',
  type: 'mainnet',
  theme: {
    colors: ['#D42D79', '#F29FB6', '#e6e6e6'],
    gradient: generateGradientColor('#d7d7d7', '#D42D79', 6),
  },
  gtag: 'G-PX7250P5WM',
  api: 'https://polkadex.webapi.subscan.io',
  domain: 'https://polkadex.subscan.io',
  subdomain: ['polkadex'],
  social: {
    telegram: 'https://t.me/Polkadex',
    twitter: 'https://twitter.com/polkadex',
    github: 'https://github.com/Polkadex-Substrate',
    price: 'https://www.coingecko.com/en/coins/polkadex',
    website: 'https://www.polkadex.trade/',
    whitePaper: '',
  },
  parachain: {
    id: 2040,
    relaychain: 'polkadot',
  },
  donate: 'espBwNTdpAxMkx9vck1ivqzbRVghtxE3TFYXYiveSV9819dUm',
  modules: {
    BOUNTY: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    EVM_NETWORK: false,
    FELLOWSHIP: false,
    GRANDPA_VOTE: false,
    MULTISIG_TOOL: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    PARATHREAD: false,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    REFERENDA_V2: false,
    SYSTEM_ACCOUNT: false,
    V2_API: false,
    V2_REWARD: false,
    VESTING: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    SS58: true,
    TREASURY_CHART: true,
    VALIDATOR: true,
  },
  disable: false,
}
