import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Quartz: Chain = {
  id: 'quartz',
  nativeTokenUniqueId: 'QTZ',
  name: 'Quartz',
  type: 'mainnet',
  theme: {
    colors: ['#EC5B6D', '#F5ADB6', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#EC5B6D', 6),
  },
  gtag: 'G-FXY14SHNH4',
  api: 'https://quartz.webapi.subscan.io',
  domain: 'https://quartz.subscan.io',
  subdomain: ['quartz'],
  social: {
    telegram: 'https://t.me/Uniquechain ',
    twitter: 'https://twitter.com/Unique_NFTchain ',
    github: 'https://github.com/UniqueNetwork ',
    price: 'https://www.coingecko.com/en/coins/quartz',
  },
  donate: 'yGGA43xUyrY68FXkhCQAnhM397m6hZ1tVLXYrLCLTEEMb71nH',
  modules: {
    SYSTEM_ACCOUNT: false,
    VESTING: true,
    GRANDPA_VOTE: true,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: true,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: true,
    VALIDATOR: false,
    SS58: true,
  },
}
