import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Reef: Chain = {
  id: 'reef',
  nativeTokenUniqueId: 'REEF',
  name: 'Reef',
  type: 'mainnet',
  theme: {
    colors: ['#681CFF', '#B08AFC', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#681CFF', 6),
  },
  gtag: 'G-5T0QM4P15N',
  api: 'https://reef.webapi.subscan.io',
  domain: 'https://reef.subscan.io',
  subdomain: ['reef'],
  social: {
    telegram: 'https://t.me/reefdefi ',
    twitter: 'https://twitter.com/ReefDeFi ',
    github: 'https://github.com/reef-defi ',
    price: 'https://www.coingecko.com/en/coins/reef',
  },
  donate: '5FVFSCANyotNxJM4Crm1LQfsmNQSw3p8H7CRbegN7d5Ex91y',
  modules: {
    SYSTEM_ACCOUNT: false,
    VESTING: false,
    GRANDPA_VOTE: false,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: false,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: false,
    VALIDATOR: true,
    SS58: true,
  },
}
