import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Robonomics: Chain = {
  id: 'robonomics',
  nativeTokenUniqueId: 'XRT',
  name: 'Robonomics',
  type: 'mainnet',
  theme: {
    colors: ['#535974', '#86C4EF', '#e6e6e6'],
    gradient: generateGradientColor('#d7d7d7', '#535974', 6),
  },
  gtag: 'G-J5J9ZRHW2Z',
  api: 'https://robonomics.webapi.subscan.io',
  domain: 'https://robonomics.subscan.io',
  subdomain: ['robonomics'],
  social: {
    telegram: 'https://t.me/robonomics ',
    twitter: 'https://twitter.com/AIRA_Robonomics ',
    github: 'https://github.com/airalab ',
    price: 'https://www.coingecko.com/en/coins/robonomics-network',
  },
  donate: '4FcerGkM8u97PiJR9XxmZQ1dJWyWPDWvPhf7SpFMV58N8fLP',
  modules: {
    SYSTEM_ACCOUNT: true,
    VESTING: true,
    GRANDPA_VOTE: true,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: true,
    EVM: false,
    PARATHREAD: true,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: true,
    VALIDATOR: false,
    SS58: true,
  },
}
