import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Rococo: Chain = {
  id: 'rococo',
  nativeTokenUniqueId: 'ROC',
  name: 'Rococo V1',
  type: 'testnet',
  theme: {
    colors: ['#E6057A', '#EE7FB9', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#E6057A', 6),
  },
  gtag: 'G-WCYHNGL36B',
  api: 'https://rococo.webapi.subscan.io',
  domain: 'https://rococo.subscan.io',
  subdomain: ['rococo'],
  social: {
    telegram: ' ',
    twitter: ' ',
    github: 'https://github.com/paritytech/polkadot ',
    price: '',
  },
  donate: '5FVFSCANyotNxJM4Crm1LQfsmNQSw3p8H7CRbegN7d5Ex91y',
  modules: {
    SYSTEM_ACCOUNT: false,
    VESTING: false,
    GRANDPA_VOTE: false,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: true,
    POLKASSEMBLY_LINK: false,
    PRICE: false,
    PRICE_HISTORY: false,
    PRICE_CONVERT: false,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: false,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: true,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: false,
    VALIDATOR: false,
    SS58: true,
  },
}
