import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Shiden: Chain = {
  id: 'shiden',
  nativeTokenUniqueId: 'SDN',
  name: 'Shiden',
  type: 'mainnet',
  theme: {
    colors: ['#5928B1', '#A990D5', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#5928B1', 6),
  },
  gtag: 'G-D6MTY4CQMJ',
  api: 'https://shiden.webapi.subscan.io',
  domain: 'https://shiden.subscan.io',
  subdomain: ['shiden'],
  social: {
    telegram: 'https://t.me/PlasmOfficial ',
    twitter: 'https://twitter.com/ShidenNetwork ',
    github: 'https://github.com/AstarNetwork/Astar ',
    price: 'https://www.coingecko.com/en/coins/shiden-network',
  },
  donate: 'ZMqsV8Tm3XVB8NthAD8N4q9rR7ZuGWsJJhZqMtDyz5CXyX7',
  modules: {
    SYSTEM_ACCOUNT: true,
    VESTING: true,
    GRANDPA_VOTE: true,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: true,
    CONTRACT_SOURCIFY: true,
    ETH_ADDRESS: true,
    EVM: true,
    PARATHREAD: true,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: false,
    WASM_CONTRACT: true,
    WASM_CONTRACT_SOURCIFY: true,
    // has hide prefix before
    TREASURY_CHART: true,
    VALIDATOR: false,
    SS58: true,
  },
}
