import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Sora: Chain = {
  id: 'sora',
  nativeTokenUniqueId: 'XOR',
  name: 'SORA',
  type: 'mainnet',
  theme: {
    colors: ['#E5232C', '#F37C7C', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#E5232C', 6),
  },
  gtag: 'G-RQYXVZPLN8',
  api: 'https://sora.webapi.subscan.io',
  domain: 'https://sora.subscan.io',
  subdomain: ['sora'],
  social: {
    telegram: ' ',
    twitter: 'https://twitter.com/sora_xor ',
    github: 'https://github.com/sora-xor ',
    price: 'https://www.coingecko.com/en/coins/sora',
  },
  donate: 'cnUuq45FYqAqw2mzXNbz3gDChbepLDNNXsnstbncKTN54vsrK',
  modules: {
    SYSTEM_ACCOUNT: false,
    VESTING: false,
    GRANDPA_VOTE: false,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: false,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: false,
    VALIDATOR: true,
    SS58: true,
  },
}
