import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Stafi: Chain = {
  id: 'stafi',
  nativeTokenUniqueId: 'FIS',
  name: 'Stafi',
  type: 'mainnet',
  theme: {
    colors: ['#272F36', '#8F9497', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#272F36', 6),
  },
  gtag: 'G-V8WP5DB7J9',
  api: 'https://stafi.webapi.subscan.io',
  domain: 'https://stafi.subscan.io',
  subdomain: ['stafi'],
  social: {
    telegram: ' ',
    twitter: 'https://twitter.com/Stafi_Protocol ',
    github: 'https://github.com/stafiprotocol/stafi-node ',
    price: 'https://www.coingecko.com/en/coins/stafi',
  },
  donate: '34AjkNFWXQePX1SrH9QV2apXYhFyj1xg8R1Y4cXjvozWknPN',
  modules: {
    SYSTEM_ACCOUNT: false,
    VESTING: true,
    GRANDPA_VOTE: true,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: false,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: true,
    VALIDATOR: true,
    SS58: true,
  },
}
