import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Subspace: Chain = {
  id: 'subspace',
  nativeTokenUniqueId: 'tSSC',
  name: 'Subspace Gemini 3D',
  type: 'testnet',
  theme: {
    colors: ['#502D89', '#9D84C6', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#502D89', 6),
  },
  gtag: 'G-1C4ZZ07QGG',
  api: 'https://subspace.webapi.subscan.io',
  domain: 'https://subspace.subscan.io',
  subdomain: ['subspace'],
  social: {
    telegram: 'https://t.me/subspace_network ',
    twitter: 'https://twitter.com/NetworkSubspace ',
    github: 'https://github.com/subspace ',
    price: '',
  },
  donate: 'st9gjWgsqgULbhvKe52QVYb9wVynuskJPJNg9tCeeuYQLnJJv',
  modules: {
    SYSTEM_ACCOUNT: false,
    VESTING: true,
    GRANDPA_VOTE: true,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: false,
    PRICE_HISTORY: false,
    PRICE_CONVERT: false,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: false,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: false,
    VALIDATOR: false,
    SS58: true,
  },
}
