import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Turing: Chain = {
  id: 'turing',
  nativeTokenUniqueId: 'TUR',
  name: 'Turing',
  type: 'mainnet',
  theme: {
    colors: ['#891D87', '#C48EC3', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#891D87', 6),
  },
  gtag: 'G-0YGTGSK3QN',
  api: 'https://turing.webapi.subscan.io',
  domain: 'https://turing.subscan.io',
  subdomain: ['turing'],
  social: {
    telegram: 'https://t.me/OAKNetworkCommunity ',
    twitter: 'https://twitter.com/oak_network ',
    github: ' ',
    price: '',
  },
  donate: '69aBm831SRkvMpzEMegDjX4hajh6RhUoyaBc8oU5HKRdV6Vj',
  modules: {
    SYSTEM_ACCOUNT: false,
    VESTING: true,
    GRANDPA_VOTE: true,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: false,
    PRICE_HISTORY: false,
    PRICE_CONVERT: false,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: true,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: true,
    VALIDATOR: false,
    SS58: true,
  },
}
