import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Unique: Chain = {
  id: 'unique',
  nativeTokenUniqueId: 'UNQ',
  name: 'Unique',
  type: 'mainnet',
  theme: {
    colors: ['#5DC0FF', '#D8F0FF', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#5DC0FF', 6),
  },
  gtag: 'G-SE4446HVPB',
  api: 'https://unique.webapi.subscan.io',
  domain: 'https://unique.subscan.io',
  subdomain: ['unique'],
  social: {
    telegram: 'https://t.me/Uniquechain ',
    twitter: 'https://twitter.com/Unique_NFTchain ',
    github: 'https://github.com/UniqueNetwork ',
    price: 'https://www.coingecko.com/en/coins/unique-network',
  },
  donate: 'unhwbuvnZWqPvkxZdcw8ow3pmbcEigoy6JYVdZXEFvyEccTVv',
  modules: {
    SYSTEM_ACCOUNT: false,
    VESTING: true,
    GRANDPA_VOTE: true,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: true,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: true,
    VALIDATOR: false,
    SS58: true,
  },
}
