import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Westend: Chain = {
  id: 'westend',
  nativeTokenUniqueId: 'WND',
  name: 'Westend',
  type: 'testnet',
  theme: {
    colors: ['#EF4C49', '#F3A2A1', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#EF4C49', 6),
  },
  gtag: 'G-MQG4DNL0W3',
  api: 'https://westend.webapi.subscan.io',
  domain: 'https://westend.subscan.io',
  subdomain: ['westend'],
  social: {
    telegram: ' ',
    twitter: ' ',
    github: ' ',
    price: '',
  },
  donate: '5FVFSCANyotNxJM4Crm1LQfsmNQSw3p8H7CRbegN7d5Ex91y',
  modules: {
    BOUNTY: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    EVM_NETWORK: false,
    FELLOWSHIP: false,
    GRANDPA_VOTE: true,
    MULTISIG_TOOL: false,
    NOMINATION_POOL: true,
    NOMINATE_FEATURE: false,
    PARACHAIN: true,
    PARATHREAD: false,
    POLKASSEMBLY_LINK: false,
    PRICE: false,
    PRICE_HISTORY: false,
    PRICE_CONVERT: false,
    REFERENDA_V2: false,
    SYSTEM_ACCOUNT: false,
    V2_API: true,
    V2_REWARD: true,
    VESTING: true,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    SS58: true,
    TREASURY_CHART: true,
    VALIDATOR: true,
  },
}
