import { generateGradientColor } from '@/utils/color'
import { Chain } from '../types'
export const Zeitgeist: Chain = {
  id: 'zeitgeist',
  nativeTokenUniqueId: 'ZTG',
  name: 'Zeitgeist',
  type: 'mainnet',
  theme: {
    colors: ['#000000', '#7F7F7F', '#d7d7d7'],
    gradient: generateGradientColor('#d7d7d7', '#000000', 6),
  },
  gtag: 'G-6TYJR388Z1',
  api: 'https://zeitgeist.webapi.subscan.io',
  domain: 'https://zeitgeist.subscan.io',
  subdomain: ['zeitgeist'],
  social: {
    telegram: 'https://t.me/zeitgeist_official ',
    twitter: 'https://twitter.com/ZeitgeistPM ',
    github: 'https://github.com/ZeitgeistPM ',
    price: 'https://www.coingecko.com/en/coins/zeitgeist',
  },
  donate: 'dE2ShE3rmDek11oZHEuC8LuHV3sRcGHZnAahW6mFPzGHtyXwn',
  modules: {
    SYSTEM_ACCOUNT: true,
    VESTING: true,
    GRANDPA_VOTE: true,
    BOUNTY: false,
    NOMINATION_POOL: false,
    NOMINATE_FEATURE: false,
    PARACHAIN: false,
    POLKASSEMBLY_LINK: false,
    PRICE: true,
    PRICE_HISTORY: true,
    PRICE_CONVERT: true,
    V2_REWARD: false,
    MULTISIG_TOOL: false,
    EVM_NETWORK: false,
    CONTRACT: false,
    CONTRACT_SOURCIFY: false,
    ETH_ADDRESS: false,
    EVM: false,
    PARATHREAD: true,
    REFERENDA_V2: false,
    FELLOWSHIP: false,
    V2_API: false,
    WASM_CONTRACT: false,
    WASM_CONTRACT_SOURCIFY: false,
    // has hide prefix before
    TREASURY_CHART: true,
    VALIDATOR: false,
    SS58: true,
  },
}
