name: Deploy staging

on:
  push:
    branches: ["develop"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Config
        id: config
        run: |
          echo "branch=develop" >> $GITHUB_ENV
          echo "commit_hash=${{ github.sha }}" >> $GITHUB_ENV
          echo "project_name=subscan-ui-next" >> $GITHUB_ENV
          echo "environment=preview" >> $GITHUB_ENV
          echo "CLOUDFLARE_API_TOKEN=${{ secrets.CF_PAGES_TOKEN }}" >> $GITHUB_ENV
          echo "CLOUDFLARE_ACCOUNT_ID=${{ secrets.CF_PAGES_ACCOUNT_ID }}" >> $GITHUB_ENV

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Build
        run: npm install && npx @cloudflare/next-on-pages@0.0.0-b33639f --experimental-minify

      - uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: '2.20.0'
          command: pages publish .vercel/output/static --project-name=${{ env.project_name }} --branch=${{ env.branch }} --commit-hash=${{ env.commit_hash }}

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ env.project_name }}
          directory: .vercel/output/static
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          append: true
          message: ${{ steps.deploy-pages.outputs.url }}

      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ID }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/14985020?s=48&v=4
          SLACK_MESSAGE: "${{ steps.deploy-pages.outputs.url }}"
          SLACK_TITLE: Preview
          SLACK_USERNAME: Pages
          SLACK_WEBHOOK: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

