name: Deploy staging

on:
  push:
    branches: ["develop"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # 15 minutes timeout
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - run: sleep 60
      - name: cloudflare-preview-url
        uses: zentered/cloudflare-preview-url@v1.4.0
        id: cloudflare_preview_url
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.PERROR_CF_PAGES_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.PERROR_CF_PAGES_ACCOUNT_ID }}
        with:
          cloudflare_project_id: subscan-ui-next
          wait_until_ready: true
          commit_hash: ${{ github.sha }}
          environment: preview

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          append: true
          message: ${{ steps.cloudflare_preview_url.outputs.preview_url }}

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ID }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/14985020?s=48&v=4
          SLACK_MESSAGE: "${{ steps.cloudflare_preview_url.outputs.preview_url }}"
          SLACK_TITLE: Preview
          SLACK_USERNAME: Pages
          SLACK_WEBHOOK: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
