name: Deploy dev

on:
  pull_request:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # 15 minutes timeout
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - run: sleep 60
      - name: cloudflare-preview-url
        uses: zentered/cloudflare-preview-url@v1.4.0
        id: cloudflare_preview_url
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.PERROR_CF_PAGES_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.PERROR_CF_PAGES_ACCOUNT_ID }}
        with:
          cloudflare_project_id: subscan-ui-next
          wait_until_ready: true
          commit_hash: ${{ github.sha }}
          environment: preview

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          append: true
          message: ${{ steps.cloudflare_preview_url.outputs.preview_url }}
