name: Deploy staging

on:
  push:
    branches: ["develop", "main"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        run: npm install && npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        id: deploy-pages
        with:
          apiToken: ${{ secrets.CF_PAGES_TOKEN }}
          accountId: ${{ secrets.CF_PAGES_ACCOUNT_ID }}
          projectName: subscan-ui-next
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: staging

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          append: true
          message: ${{ steps.deploy-pages.outputs.url }}

      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ID }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/14985020?s=48&v=4
          SLACK_MESSAGE: "${{ steps.deploy-pages.outputs.url }}"
          SLACK_TITLE: Preview
          SLACK_USERNAME: Pages
          SLACK_WEBHOOK: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
